<?php
header('Content-Type: application/json; charset=utf-8');
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); echo json_encode(['error'=>'POST required']); exit; }
$body=json_decode(file_get_contents('php://input'),true)?:[]; $thLevel=(int)($body['townHall']??0);
if($thLevel<1||$thLevel>18){http_response_code(400);echo json_encode(['error'=>'Invalid Town Hall']);exit;}
$data=json_decode(file_get_contents(__DIR__.'/../data/game-data.json'),true); if(!$data){http_response_code(500);echo json_encode(['error'=>'Game data unavailable']);exit;}
$th=null; foreach($data['townHalls'] as $x)if((int)$x['level']===$thLevel)$th=$x; if(!$th){http_response_code(404);echo json_encode(['error'=>'Town Hall data not found']);exit;}
function bmax($th,$b){$m=['Barrack'=>'maxBarracks','Dark Barrack'=>'maxDarkBarracks','Spell Factory'=>'maxSpellFactory','Dark Spell Factory'=>'maxDarkSpellFactory','Workshop'=>'maxWorkshop'];$k=$m[$b]??null;return $k?($th[$k]??null):null;}
function avail($items,$th){$o=[];foreach($items as $u){$best=null;foreach(($u['levels']??[]) as $l){$b=bmax($th,$u['productionBuilding']??'');$okb=$b===null||((int)($l['buildingLevel']??0)<=(int)$b);$okl=(int)($l['laboratoryLevel']??0)<=(int)($th['maxLaboratory']??0);if($okb&&$okl)$best=$l;}if($best)$o[]=['name'=>$u['name'],'housingSpace'=>(int)($u['housingSpace']??0),'maxLevel'=>(int)($best['level']??1),'isSuper'=>(bool)($u['isSuper']??false)];}return $o;}
function simple($items,$th,$field){$o=[];$max=$field==='pet'?($th['maxPetHouse']??null):($th['maxBlacksmith']??null);foreach($items as $u){$best=null;foreach(($u['levels']??[]) as $l){$r=(int)($l[$field==='pet'?'petHouseLevel':'blacksmithLevel']??0);if($max!==null&&$r<=(int)$max)$best=$l;}if($best)$o[]=['name'=>$u['name'],'maxLevel'=>(int)($best['level']??1)];}return $o;}
$allowed=['townHall'=>$thLevel,'capacity'=>['troops'=>(int)$th['troopCapacity'],'spells'=>(int)$th['spellCapacity'],'siege'=>(int)$th['siegeCapacity'],'ccTroops'=>(int)$th['ccTroopCapacity'],'ccSpells'=>(int)$th['ccSpellCapacity'],'ccSiege'=>(int)$th['ccSiegeCapacity']],'troops'=>avail($data['troops'],$th),'spells'=>avail($data['spells'],$th),'sieges'=>array_map(fn($s)=>['name'=>$s['name']],array_filter($data['sieges'],fn($s)=>(int)$th['siegeCapacity']>0)),'heroes'=>$th['heroMaxLevels'],'pets'=>simple($data['pets'],$th,'pet'),'equipment'=>simple($data['equipment'],$th,'equipment')];
$api=getenv('AI_API_URL');$key=getenv('AI_API_KEY');$model=getenv('AI_MODEL');
if(!$api||!$key||!$model){http_response_code(503);echo json_encode(['error'=>'AI provider is not configured. Set AI_API_URL, AI_API_KEY and AI_MODEL on the server.']);exit;}
$system='You are a Clash of Clans army composition engine. Use ONLY supplied validated game data. Return JSON only: armyName,troops[{name,quantity}],spells[{name,quantity}],siegeMachine,clanCastle{troops,spells},heroes[],pets[],equipment[],strategy[]. Never invent names. Never exceed troop or spell capacity. Prefer a coherent war attack.';
$payload=['model'=>$model,'messages'=>[['role'=>'system','content'=>$system],['role'=>'user','content'=>'Create one coherent army for TH'.$thLevel.'. Valid data: '.json_encode($allowed,JSON_UNESCAPED_SLASHES)]],'temperature'=>0.25,'response_format'=>['type'=>'json_object']];
$ch=curl_init($api);curl_setopt_array($ch,[CURLOPT_POST=>1,CURLOPT_RETURNTRANSFER=>1,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$key],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>45]);$res=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($res===false||$code<200||$code>=300){http_response_code(502);echo json_encode(['error'=>'AI provider request failed','status'=>$code]);exit;}
$r=json_decode($res,true);$content=$r['choices'][0]['message']['content']??null;$army=json_decode($content,true);if(!$army){http_response_code(502);echo json_encode(['error'=>'AI returned invalid JSON']);exit;}
$tm=[];foreach($allowed['troops'] as $x)$tm[$x['name']]=$x['housingSpace'];$sm=[];foreach($allowed['spells'] as $x)$sm[$x['name']]=$x['housingSpace'];$tu=0;$su=0;foreach(($army['troops']??[]) as $x){$n=$x['name']??'';$q=(int)($x['quantity']??0);if(!isset($tm[$n])||$q<0){http_response_code(422);echo json_encode(['error'=>'Invalid troop','unit'=>$n]);exit;}$tu+=$tm[$n]*$q;}foreach(($army['spells']??[]) as $x){$n=$x['name']??'';$q=(int)($x['quantity']??0);if(!isset($sm[$n])||$q<0){http_response_code(422);echo json_encode(['error'=>'Invalid spell','unit'=>$n]);exit;}$su+=$sm[$n]*$q;}if($tu>$allowed['capacity']['troops']||$su>$allowed['capacity']['spells']){http_response_code(422);echo json_encode(['error'=>'Army exceeds capacity','troopUsed'=>$tu,'troopCapacity'=>$allowed['capacity']['troops'],'spellUsed'=>$su,'spellCapacity'=>$allowed['capacity']['spells']]);exit;}$army['usage']=['troops'=>$tu,'troopCapacity'=>$allowed['capacity']['troops'],'spells'=>$su,'spellCapacity'=>$allowed['capacity']['spells']];echo json_encode($army,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
